In [44]:
import pandas as pd
import numpy as np
import os
import sys
import glob
from datetime import datetime
# Make `src` dir can be imported
project_root_path = os.path.abspath(os.path.join(os.getcwd(), '..'))  # /aicup-predict-energy-generation
sys.path.append(project_root_path)



import matplotlib.pyplot as plt
import seaborn as sns

from src.fe_tools import create_time_features

In [58]:
# df_test5_result = pd.read_csv('../pred_results/Sean/test_5_L10_pe_result.csv')
df_test5_result = pd.read_csv('../pred_results/Sean/test_6_L10_sunlight_sim_result.csv')
df_test6_result = pd.read_csv('../pred_results/Sean/test_8_L10_sunlight_sim_result.csv')


df_test5_result = create_time_features(df_test5_result)
df_test6_result = create_time_features(df_test6_result)

In [59]:
date_select = pd.Timestamp(2024, 7, 4).date()

df_test5_sel = df_test5_result[df_test5_result['date'] == date_select]
df_test6_sel = df_test6_result[df_test6_result['date'] == date_select]

In [60]:
df_test5_result.tae.sum()

np.float64(1074528.2825796406)

In [61]:
df_test6_sel.tae.sum()

np.float64(113939.01627804287)

In [62]:
def result_comparsion(df1, df2):
    df1_groupby = df1.groupby(['date']).agg(tae1=('tae','sum')).reset_index()
    df2_groupby = df2.groupby(['date']).agg(tae2=('tae','sum')).reset_index()

    df_merge = pd.merge(df1_groupby , df2_groupby, how='left', on='date')

    df_merge['tae_diff'] = df_merge['tae2'] - df_merge['tae1']

    return df_merge

In [63]:
result_comparsion(df_test5_result, df_test6_result)

          date           tae1           tae2     tae_diff
0   2024-06-30    7586.738378    7449.408554  -137.329824
1   2024-07-01  103474.862186  103734.094935   259.232748
2   2024-07-02   84981.551113   86123.336966  1141.785852
3   2024-07-03   66389.500664   65622.965363  -766.535301
4   2024-07-04  113861.525939  113939.016278    77.490339
5   2024-07-05  108657.284141  107486.168297 -1171.115844
6   2024-07-06   91857.851310   90792.307987 -1065.543322
7   2024-07-07   92790.245053   92399.497163  -390.747890
8   2024-07-08   28426.392970   27623.084867  -803.308103
9   2024-07-10   28196.210666   29309.061911  1112.851245
10  2024-07-11    1209.562082    1133.744905   -75.817178
11  2024-07-12   61539.692990   60179.903563 -1359.789427
12  2024-07-13   78728.386959   78853.742339   125.355380
13  2024-07-14    2597.664037    2463.677714  -133.986322
14  2024-07-15   55560.072159   56725.807789  1165.735631
15  2024-07-16   47738.248371   41379.648986 -6358.599385
16  2024-07-17   30929.809989   36947.607680  6017.797691
17  2024-07-18    1609.067695    1863.210097   254.142403
18  2024-07-19   26068.426580   24632.683272 -1435.743308
19  2024-07-20     991.596447    1004.141506    12.545059
20  2024-07-21   41333.592852   41231.934631  -101.658220